In [1]:
import nccm_enrichment
import pandas as pd

# Window-based approach

In [ ]:
# List covariates to be used in the model
param_covariates = ['scaled_log_ncncm_rate']+\
                   ['scaled_log_perc_gc','scaled_log_perc_cpg', 'scaled_log_perc_tpc', 'scaled_log_perc_tpa']+\
                   ['scaled_log_perc_open']+\
                   ['scaled_yeo_rep']+['scaled_yeo_phylop'] +['scaled_log_expr']

In [14]:
# Load the NCCM scan data and covariates
scan_df = nccm_enrichment.load_data('/Users/rappe860/Documents/work/NCCM-significance/hg19v3/3.negbin_regression/runs/w2kbp_phylop1.2/pancancer_ALL_whitelisted_nohyper_excl_melanoma_blood_n2101.2kbp_windows.phylop-1.2.scan.tsv')
covariates = nccm_enrichment.load_data('../data/hg19/hg19.2kbp_windows.covariates.tsv')#, w2k_expr_path]])

# Merge dfs and filter excluded genes
exclude = nccm_enrichment.load_data('../data/hg19/hg19.2kbp_windows.excluded_genes.txt')['gene'].tolist()
total_df = nccm_enrichment.merge_dfs_on_gene(scan_df, covariates)
total_df_filt = total_df[~total_df['gene'].isin(exclude)]

In [ ]:
# Define covariates to include in the model
covariates_list = param_covariates

# Update the parameters for the approach
params = nccm_enrichment.ModelParams(covariates_list=covariates_list, n_bins=10)

# Run the window-based approach
results_windows = nccm_enrichment.window_based_approach(total_df_filt, params)

In [16]:
results_windows[results_windows['q_value']<0.1][['gene','closest_gene','q_value']]

                            gene closest_gene       q_value
966641   2kbp_window_chr18_56120        ALPK2  2.286571e-29
1050588  2kbp_window_chr18_56119        ALPK2  2.112287e-25
847032    2kbp_window_chr4_74280          ALB  7.102123e-23
490635    2kbp_window_chr4_74273          ALB  9.215567e-19
787100    2kbp_window_chr4_74277          ALB  3.695218e-15
...                          ...          ...           ...
1388001  2kbp_window_chr9_118546        PAPPA  9.365709e-02
557366   2kbp_window_chr16_20383        PDILT  9.365709e-02
1404426  2kbp_window_chr6_165013     C6orf118  9.497408e-02
1564141  2kbp_window_chr3_101949        ZPLD1  9.497408e-02
1175706  2kbp_window_chr15_95121        MCTP2  9.511097e-02

[81 rows x 3 columns]

# Gene-centric approach

In [17]:
# List covariates to be used in the model
param_covariates = ['scaled_log_ncncm_rate']+\
                   ['scaled_log_perc_gc','scaled_log_perc_cpg', 'scaled_log_perc_tpc', 'scaled_log_perc_tpa']+\
                   ['scaled_log_perc_open']+\
                   ['scaled_yeo_rep']+['scaled_yeo_phylop'] +['scaled_log_expr']

In [ ]:
# Load the NCCM scan data and covariates for different flank sizes
scan_df_100 = nccm_enrichment.load_data('/Users/rappe860/Documents/work/NCCM-significance/hg19v3/3.negbin_regression/runs/f100kbp_phylop1.2/pancancer_ALL_whitelisted_nohyper_excl_melanoma_blood_n2101.phylop-1.2.scan.tsv')
scan_df_50 = nccm_enrichment.load_data('/Users/rappe860/Documents/work/NCCM-significance/hg19v3/3.negbin_regression/runs/f50kbp_phylop1.2/pancancer_ALL_whitelisted_nohyper_excl_melanoma_blood_n2101.50kbp_flanks.phylop-1.2.scan.tsv')
scan_df_10 = nccm_enrichment.load_data('/Users/rappe860/Documents/work/NCCM-significance/hg19v3/3.negbin_regression/runs/f10kbp_phylop1.2/pancancer_ALL_whitelisted_nohyper_excl_melanoma_blood_n2101.10kbp_flanks.phylop-1.2.scan.tsv')
scan_df_5 = nccm_enrichment.load_data('/Users/rappe860/Documents/work/NCCM-significance/hg19v3/3.negbin_regression/runs/f5kbp_phylop1.2/pancancer_ALL_whitelisted_nohyper_excl_melanoma_blood_n2101.5kbp_flanks.phylop-1.2.scan.tsv')

exclude_100 = nccm_enrichment.load_data('../data/hg19/hg19_gene_100kb_flanks.excluded_genes.txt')['gene'].tolist()
exclude_50 = nccm_enrichment.load_data('../data/hg19/hg19_gene_50kb_flanks.excluded_genes.txt')['gene'].tolist()
exclude_10 = nccm_enrichment.load_data('../data/hg19/hg19_gene_10kb_flanks.excluded_genes.txt')['gene'].tolist()
exclude_5 = nccm_enrichment.load_data('../data/hg19/hg19_gene_5kb_flanks.excluded_genes.txt')['gene'].tolist()

covariates_100 = nccm_enrichment.load_data('../data/hg19/hg19.100kbp_flanks.covariates.tsv')#, w2k_expr_path]])
covariates_50 = nccm_enrichment.load_data('../data/hg19/hg19.50kbp_flanks.covariates.tsv')#, w2k_expr_path]])
covariates_10 = nccm_enrichment.load_data('../data/hg19/hg19.10kbp_flanks.covariates.tsv')#, w2k_expr_path]])
covariates_5 = nccm_enrichment.load_data('../data/hg19/hg19.5kbp_flanks.covariates.tsv')#, w2k_expr_path]])

# Merge and filter the dfs
total_df_100 = nccm_enrichment.merge_dfs_on_gene(scan_df_100, covariates_100)
total_df_filt_100 = total_df_100[~total_df_100['gene'].isin(exclude_100)]

total_df_50 = nccm_enrichment.merge_dfs_on_gene(scan_df_50, covariates_50)
total_df_filt_50 = total_df_50[~total_df_50['gene'].isin(exclude_50)]

total_df_10 = nccm_enrichment.merge_dfs_on_gene(scan_df_10, covariates_10)
total_df_filt_10 = total_df_10[~total_df_10['gene'].isin(exclude_10)]

total_df_5 = nccm_enrichment.merge_dfs_on_gene(scan_df_5, covariates_5)
total_df_filt_5 = total_df_5[~total_df_5['gene'].isin(exclude_5)]

# Define covariates to include in the model
covariates_list = param_covariates

# Update the parameters for the approach
params = nccm_enrichment.ModelParams(covariates_list=covariates_list, n_bins=10)

# Run the gene-centric approach
results_flanks = nccm_enrichment.gene_centric_approach(total_df_filt_100,total_df_filt_50, total_df_filt_10, total_df_filt_5, params=params)

In [19]:
results_flanks[results_flanks['q_brown_gc']<0.1][['gene','q_brown_gc']]

           gene    q_brown_gc
13099       ALB  3.139433e-10
13125       AFP  9.427839e-07
7548       HES1  7.873022e-03
7757      WDR74  2.318733e-02
4955       RBM4  2.318733e-02
13425    TRIM27  2.318733e-02
12997       AFM  3.147473e-02
4583      RBM4B  3.147473e-02
4552      MED16  3.561239e-02
7620      TRIM7  5.025877e-02
10118  CASP8AP2  6.057341e-02
11134     FOXA1  6.057341e-02
14581     CSMD1  6.674359e-02
8461    GALNTL5  7.212938e-02